stack_name: ""

image:
  url: 149536470129.dkr.ecr.us-east-1.amazonaws.com
  name: ticketpeak
  tag: production

app:
  is_network_service: true
  volume_id:
  command: []
  pod:
    initialCount: 7
    port: 8080
    livenessPath: /livez
    readinessPath: /readyz
  service:
    name: ticketpeak-app-production
    protocol: TCP
    port: 8080
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "6Gi"
      cpu: "2000m"
  secretName: ticketpeak-app-production
  database_secret_names_to_use: []

iam:
  service_account_role: arn:aws:iam::149536470129:role/ticketpeak-app-production
  service_account_name: ticketpeak-app-production

env_bucket_name: 149536470129-ticketpeak-env

efs:
  file_system_id: fs-0890123efbef63eb1
