apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.app.service.name }}-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          {{ if .Values.iam.service_account_name }}
          serviceAccountName: {{ .Values.iam.service_account_name }}
          {{ end }}
          terminationGracePeriodSeconds: 30
          shareProcessNamespace: true
          volumes:
            - name: efs
              persistentVolumeClaim:
                claimName: efs-pv-{{ .Release.Namespace }}
          nodeSelector:
            ticketpeak/node_type: { { .Release.Namespace } }
          tolerations:
            - key: "ticketpeak/node_type"
              operator: "Equal"
              value: "{{ .Release.Namespace }}"
              effect: "NoSchedule"
          containers:
            - name: {{ .Values.app.service.name }}-job
              image: "{{ .Values.image.url }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
              volumeMounts:
                - name: efs
                  mountPath: /var/www/html/storage
              imagePullPolicy: Always
              command:
                - "/bin/bash"
                - "-c"
                - "aws s3 cp s3://149536470129-ticketpeak-env/{{ .Release.Namespace }}/.env /var/www/html/.env && /var/www/html/jobs.sh"
              ports:
                - containerPort: {{ .Values.app.pod.port }}
              resources:
                requests:
                  memory: 1024
                  cpu: 4096
                limits:
                  memory: 1024
                  cpu: 4096
              envFrom:
                - secretRef:
                    name: {{ .Values.app.secretName }}
              securityContext:
                capabilities:
                  drop:
                    - all
          restartPolicy: Never