apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.service.name }}-webapp
spec:
  replicas: {{ .Values.app.pod.initialCount }}
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: {{ .Values.app.service.name }}-webapp
  template:
    metadata:
      labels:
        app: {{ .Values.app.service.name }}-webapp
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ .Values.app.service.name }}-webapp
              topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Values.app.service.name }}-webapp
                topologyKey: "topology.kubernetes.io/zone"
      {{- if .Values.iam.service_account_name }}
      serviceAccountName:  {{ .Values.iam.service_account_name }}
      {{ end }}
      terminationGracePeriodSeconds: 30
      shareProcessNamespace: true
      volumes:
        - name: apache-logs
          emptyDir: { }
        - name: efs
          persistentVolumeClaim:
            claimName: efs-pv-{{ .Release.Namespace }}
        - name: parsers
          configMap:
            name: fluent-bit-parsers
        - name: var-lock
          emptyDir: { }
      nodeSelector:
        ticketpeak/node_type: {{ .Release.Namespace }}
      tolerations:
        - key: "ticketpeak/node_type"
          operator: "Equal"
          value: "{{ .Release.Namespace }}"
          effect: "NoSchedule"
      containers:
      - name: {{ .Values.app.service.name }}-webapp
        image: "{{ .Values.image.url }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        volumeMounts:
          - name: efs
            mountPath: /var/www/html/storage
          - name: apache-logs
            mountPath: /var/log/apache
          - mountPath: /run/lock
            name: var-lock
        imagePullPolicy: Always
        command:
          - "/bin/bash"
          - "-c"
          - "aws s3 cp s3://149536470129-ticketpeak-env/{{ .Release.Namespace }}/.env /var/www/html/.env && /var/www/html/startup.sh"
        ports:
          - containerPort: {{ .Values.app.pod.port }}
        {{ if .Values.app.is_network_service }}
        livenessProbe:
          httpGet:
            path: {{ .Values.app.pod.healthCheckPath }}
            port: {{ .Values.app.pod.port }}
          timeoutSeconds: 10
          initialDelaySeconds: 90
        readinessProbe:
          httpGet:
            path: {{ .Values.app.pod.healthCheckPath }}
            port: {{ .Values.app.pod.port }}
          timeoutSeconds: 10
          initialDelaySeconds: 90
          successThreshold: 2
        {{ end }}
        resources:
          requests:
            memory: {{ .Values.app.resources.requests.memory }}
            cpu: {{ .Values.app.resources.requests.cpu }}
          limits:
            memory: {{ .Values.app.resources.limits.memory }}
            cpu: {{ .Values.app.resources.limits.cpu }}
        envFrom:
          - secretRef:
              name: {{ .Values.app.secretName }}
        securityContext:
          capabilities:
            drop:
              - all
      - name: fluent-bit-sidecar
        image: amazon/aws-for-fluent-bit:latest
        env:
          - name: AWS_REGION
            value: "us-east-1"
        volumeMounts:
          - name: apache-logs
            mountPath: /var/log/apache
          - name: parsers
            mountPath: /fluent-bit/etc/parsers.conf
            subPath: parsers.conf
        command:
          - /fluent-bit/bin/fluent-bit
          - -v
          - -i
          - tail
          - -p
          - path=/var/log/apache/access_log
          - -p
          - parser=apache
          - -p
          - tag=apache.access
          - -i
          - tail
          - -p
          - path=/var/log/apache/error_log
          - -p
          - tag=apache.error
          - -o
          - cloudwatch_logs
          - -p
          - region=us-east-1
          - -p
          - log_group_name=/aws/eks/{{ .Release.Namespace }}/
          - -p
          - log_stream_prefix=${HOSTNAME}
          - -p
          - auto_create_group=true
          - -p
          - Match=*
          - -R
          - /fluent-bit/etc/parsers.conf
      restartPolicy: Always
status: { }
