apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-ebs-{{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 300Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: {{ .Values.app.volume_id }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - us-east-1a

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-ebs-{{ .Release.Namespace }}
spec:
  storageClassName: ""
  volumeName: webapp-ebs-{{ .Release.Namespace }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
