apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: webapp-ebs-{{ .Release.Namespace }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.kubernetes.io/zone
        values:
          - us-east-1a
parameters:
  type: gp3
  encrypted: "true"


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-ebs-{{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: webapp-ebs-{{ .Release.Namespace }}
  resources:
    requests:
      storage: 300Gi