kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-pv-{{ .Release.Namespace }}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.efs.file_system_id }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-{{ .Release.Namespace }}
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-pv-{{ .Release.Namespace }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efs.file_system_id }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pv-{{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-pv-{{ .Release.Namespace }}
  resources:
    requests:
      storage: 200Gi