apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-parsers
data:
  parsers.conf: |
    [PARSER]
      Name   apache
      Format regex
      Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>[A-Z]+) (?<path>[^ ]*) (?<protocol>[^\"]*)" (?<status_code>[0-9]{3}) (?<size>[0-9]+|-) "(?<referrer>[^\"]*)" "(?<agent>[^\"]*)"
      Time_Key time
      Time_Format %d/%b/%Y:%H:%M:%S %z
