apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app.service.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.service.name }}-webapp
  minReplicas: {{ .Values.app.pod.initialCount }}
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50