apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaler
spec:
  scaleTargetRef:
    name: {{ .Values.app.service.name }}-webapp
  minReplicaCount: 3
  maxReplicaCount: 10
  pollingInterval: 5
  cooldownPeriod: 900
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"

    - type: memory
      metricType: Utilization
      metadata:
        value: "50"
