apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaler
spec:
  scaleTargetRef:
    name: {{ .Values.app.service.name }}-webapp
  minReplicaCount: 5
  maxReplicaCount: 15
  pollingInterval: 30
  cooldownPeriod: 180
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 180
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 900
      selectPolicy: Min
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "75"
    - type: memory
      metricType: Utilization
      metadata:
        value: "75"
