apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaler
spec:
  scaleTargetRef:
    name: {{ .Values.app.service.name }}-webapp
  minReplicaCount: 5
  maxReplicaCount: 7
  pollingInterval: 30
  cooldownPeriod: 180
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 180
    scaleDown:
      stabilizationWindowSeconds: 300
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"
    - type: memory
      metricType: Utilization
      metadata:
        value: "50"
