apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.service.name }}-log-streamer
spec:
  revisionHistoryLimit: 3
  replicas: 1
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: {{ .Values.app.service.name }}-log-streamer
  template:
    metadata:
      labels:
        app: {{ .Values.app.service.name }}-log-streamer
    spec:
      {{- if .Values.iam.service_account_name }}
      serviceAccountName:  {{ .Values.iam.service_account_name }}
      {{ end }}
      terminationGracePeriodSeconds: 30
      shareProcessNamespace: true
      volumes:
        - name: efs
          persistentVolumeClaim:
            claimName: efs-pv-{{ .Release.Namespace }}
        - name: parsers
          configMap:
            name: fluent-bit-parsers
      containers:
      - name: fluent-bit-laravel-log-streamer
        image: amazon/aws-for-fluent-bit:latest
        env:
          - name: AWS_REGION
            value: "us-east-1"
        volumeMounts:
          - name: efs
            mountPath: /var/www/html/storage
          - name: parsers
            mountPath: /fluent-bit/etc/parsers.conf
            subPath: parsers.conf
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "250m"
        command:
          - /fluent-bit/bin/fluent-bit
          - -v
          - -R
          - /fluent-bit/etc/parsers.conf
          - -i
          - tail
          - -p
          - path=/var/www/html/storage/logs/laravel_json.log
          - -p
          - DB=/var/www/html/storage/logs/.fluent-bit-laravel-json-log.db
          - -p
          - DB.sync=Normal
          - -p
          - DB.locking=true
          - -p
          - read_from_head=false
          - -p
          - refresh_interval=5
          - -p
          - inotify_watcher=false
          - -p
          - tag=laravel_json.log
          - -F
          - parser
          - -p
          - Match=laravel_json.log
          - -p
          - Key_Name=log
          - -p
          - Parser=json
          - -p
          - Reserve_Data=true
          - -o
          - cloudwatch_logs
          - -p
          - region=us-east-1
          - -p
          - log_group_name=/aws/eks/{{ .Release.Namespace }}/
          - -p
          - log_stream_prefix=${HOSTNAME}
          - -p
          - auto_create_group=true
          - -p
          - Match=*
      restartPolicy: Always
status: { }
