apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.app.service.name }}
spec:
  maxUnavailable: 1
  minAvailable: {{ .Values.app.pod.initialCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.service.name }}