apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-ticketpeak-env
spec:
  capacity:
    storage: 1200Gi # Ignored, required
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name }}-ticketpeak-env
  mountOptions:
    - allow-delete
    - region us-east-1
    - uid=1000
    - gid=1000
    - allow-other
  csi:
    driver: s3.csi.aws.com # Required
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: {{ .Values.env_bucket_name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ticketpeak-env
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi # Ignored, required
  volumeName: {{ .Release.Name }}-ticketpeak-env